---ex1
SELECT name FROM city
WHERE population>120000
AND countrycode = 'USA';
---ex2
SELECT * FROM city
WHERE countrycode = 'JPN';
---ex3
SELECT city, state FROM station;
---ex4
SELECT city FROM station
WHERE city LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%';
---ex5
SELECT DISTINCT CITY FROM STATION
WHERE city LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u';
---ex 6
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%';
---ex 7
SELECT NAME FROM EMPLOYEE
ORDER BY NAME;
---ex 8
SELECT NAME FROM EMPLOYEE
WHERE SALARY>2000 
AND MONTHS<10
ORDER BY EMPLOYEE_ID;
